book_id_start: 1
book_id_end: 81
source_lang: "en"
target_lang: "ru, es"

steps:
  preprocess: false
  sentence_split: false
  paragraph_split: false
  paragraph_split_manual: false
  chapter_split: false
  simplify_text: false
  check_preparation: false
  translate_sentences: false                         # 🔠 перевод original текста
  translate_sentences_simplified: false              # 🔠 перевод адаптированного текста
  translate_words: false                              # 🔠 добавление слов и их перевод
  translate_words_simplified: false                   # 🔠 добавление слов и их перевод к адапированному тексту
  tasks_true_or_false: true
  tasks_true_or_false_simplified: true
  tasks_how_to_translate: true
  tasks_how_to_translate_simplified: true
  tasks_two_words: true
  tasks_two_words_simplified: true
  export: false

  voice_narration: false
  voice_narration_simplified: false

  # chapters_goals: false
  # chapters_goals_simplified: false


limits:
  max_chars_per_request: 200000

options:
  log_voice: false
  max_voiced_paragraphs: 3                           # сколько абзацев озвучить: -1 безлимит
  workers: 10