book_id_start: 1
book_id_end: 81
source_lang: "en"
target_lang: "ru, es, fr, de, it"

steps:
  preprocess: false
  sentence_split: false
  paragraph_split: false
  paragraph_split_manual: false
  chapter_split: false
  simplify_text: false
  translate_sentences: true                         # 🔠 перевод original текста
  translate_sentences_simplified: true              # 🔠 перевод адаптированного текста
  translate_words: false
  translate_words_simplified: false
  tasks_true_or_false: false
  tasks_true_or_false_simplified: false
  tasks_how_to_translate: false
  tasks_how_to_translate_simplified: false
  tasks_two_words: false
  tasks_two_words_simplified: false
  export: false

  voice_narration: false
  voice_narration_simplified: false

  # chapters_goals: false
  # chapters_goals_simplified: false


limits:
  max_chars_per_request: 200000

options:
  log_voice: true
  max_voiced_paragraphs: -1                           # сколько абзацев озвучить: -1 безлимит
